---
abstract: 'Event-driven FSA for beanstalk queues'
author:
  - 'Scott Wiersdorf <scott@perlcode.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Beanstalk-Worker
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '7.05'
  AnyEvent::Beanstalk: '1.123530'
version: '0.03'
